[workspace]
resolver = "2"
members = [
    "brick",
    "brick-fmt", "brick-ld",
    "brick-lsp",
    "brick-runtime",
    "brick-wasm-backend",
    "brick-wasmc",
    "brick-wasmtime",
    "data-test-driver",
    "runtime-binary", "rust-wasm-exporter",
]
