use crate::{
    id::{NodeID, VariableID},
    ExpressionType,
};

use super::{HirModule, HirNode, HirNodeValue};

/**
 * Intentionally insert gaps between calculating return value and actually returning so borrowck
 * can insert drop points between (e.g. return arr[i] -> we should calculate the index, then
 * drop arr, then return)
 */
pub fn break_up_complex_returns(module: &mut HirModule) {
    module.par_visit_mut(|_, node| {
        let HirNodeValue::Return(Some(inner)) = &mut node.value else {
            return;
        };
        // Minor optimization, these values are guaranteed to not cause drop problems
        if let HirNodeValue::Int(_)
        | HirNodeValue::Float(_)
        | HirNodeValue::Null
        | HirNodeValue::Bool(_)
        | HirNodeValue::PointerSize(_)
        | HirNodeValue::CharLiteral(_)
        | HirNodeValue::StringLiteral(_)
        | HirNodeValue::VariableReference(_) = &inner.value
        {
            return;
        }
        let temporary_var_id = VariableID::new();
        let ty = inner.ty.clone();
        let provenance = inner.provenance.clone();
        let lhs = HirNode::autogenerated(
            HirNodeValue::VariableReference(temporary_var_id.into()),
            ty.clone(),
        );
        let sequence = vec![
            HirNode::autogenerated(HirNodeValue::Declaration(temporary_var_id), ty.clone()),
            HirNode {
                id: NodeID::new(),
                value: HirNodeValue::Assignment(
                    Box::new(lhs.clone()),
                    Box::new(std::mem::take(inner)),
                ),
                ty: ExpressionType::Void,
                provenance,
            },
            HirNode {
                id: NodeID::new(),
                value: HirNodeValue::Return(Some(Box::new(lhs))),
                ty: node.ty.clone(),
                provenance: node.provenance.clone(),
            },
        ];
        node.value = HirNodeValue::Sequence(sequence);
    });
}
