use crate::{
    id::NodeID,
    typecheck::{
        fully_dereference, CollectionType, ExpressionType, InterfaceType, PointerKind,
        PrimitiveType, StructType, TypeDeclaration, UnionType,
    },
    DeclarationContext,
};

use super::{HirNode, HirNodeValue};

pub fn rewrite(declarations: &DeclarationContext, root: &mut HirNode) {
    // We only care about function calls that are an access on the left hand side
    let HirNodeValue::Call {
        func: call_lhs,
        args,
        type_parameter_resolutions: _,
    } = &mut root.value
    else {
        return;
    };
    let root_ty = &root.ty;
    let HirNodeValue::Access(lhs, func_name) = &mut call_lhs.value else {
        return;
    };
    match fully_dereference(&lhs.ty) {
        ExpressionType::InstanceOf(ty_id) | ExpressionType::ReferenceToType(ty_id) => {
            match declarations.id_to_decl.get(ty_id) {
                None => unreachable!("ICE: type ID not found ({ty_id:?})"),
                Some(
                    TypeDeclaration::Struct(StructType {
                        associated_functions,
                        ..
                    })
                    | TypeDeclaration::Union(UnionType {
                        associated_functions,
                        ..
                    }),
                ) => {
                    if let Some(func_id) = associated_functions.get(func_name) {
                        // Replace the existing left hand side with a reference to the called function
                        let mut temporary = HirNode::autogenerated(
                            HirNodeValue::VariableReference((*func_id).into()),
                            ExpressionType::ReferenceToFunction(*func_id),
                        );
                        std::mem::swap(&mut temporary, call_lhs);
                        // Insert the struct as a parameter to the newly called function
                        let call_lhs = temporary;
                        let HirNodeValue::Access(lhs, _) = call_lhs.value else {
                            unreachable!();
                        };
                        let mut lhs = *lhs;
                        // Automatically take a reference if necessary
                        let func_ty = &declarations.id_to_func[func_id];
                        if let ExpressionType::Pointer(kind, _) = &func_ty.params[0] {
                            if !matches!(&lhs.ty, ExpressionType::Pointer(_, _)) {
                                let inner_ty = lhs.ty.clone();
                                let provenance = lhs.provenance.clone();
                                lhs = HirNode {
                                    id: NodeID::new(),
                                    value: HirNodeValue::TakePointer(*kind, Box::new(lhs)),
                                    ty: ExpressionType::Pointer(*kind, Box::new(inner_ty)),
                                    provenance,
                                };
                            }
                        }
                        args.insert(0, lhs);
                    }
                }
                Some(TypeDeclaration::Interface(InterfaceType {
                    associated_functions,
                    ..
                })) => {
                    if let Some(fn_id) = associated_functions.get(func_name) {
                        // TODO: restore this?
                        // Insert the interface as a parameter to itself
                        args.insert(
                            0,
                            HirNode::autogenerated(
                                HirNodeValue::InterfaceAddress(lhs.clone()),
                                ExpressionType::Primitive(PrimitiveType::PointerSize),
                            ),
                        );

                        let mut temp = HirNode::dummy();
                        std::mem::swap(&mut temp, root);
                        let HirNode {
                            id,
                            value:
                                HirNodeValue::Call {
                                    func: lhs,
                                    args,
                                    type_parameter_resolutions: _,
                                },
                            ty,
                            provenance: _,
                        } = temp
                        else {
                            unreachable!()
                        };
                        let HirNodeValue::Access(lhs, _func_name) = lhs.value else {
                            unreachable!()
                        };
                        temp = HirNode::generated_with_id(
                            id,
                            HirNodeValue::VtableCall(lhs, *fn_id, args),
                            ty,
                        );
                        std::mem::swap(&mut temp, root);
                    }
                }
                Some(TypeDeclaration::TypeParameter(_)) => {
                    let ty_id = *ty_id;
                    let HirNodeValue::Access(lhs, name) = &mut call_lhs.value else {
                        unreachable!();
                    };
                    // TODO: given the type parameter, determine what bound this function
                    // call has. then determine which reference type to take, if necessary.
                    let lhs = std::mem::take(lhs);
                    let kind = PointerKind::SharedRef;
                    let lhs_ty = lhs.ty.clone();
                    let lhs_provenance = lhs.provenance.clone();
                    let lhs = Box::new(HirNode {
                        id: NodeID::new(),
                        value: HirNodeValue::TakePointer(kind, lhs),
                        ty: ExpressionType::Pointer(kind, Box::new(lhs_ty)),
                        provenance: lhs_provenance,
                    });
                    let name = std::mem::take(name);
                    let args = std::mem::take(args);
                    root.value = HirNodeValue::TypeParameterCall(ty_id, name, lhs, args);
                }
                Some(TypeDeclaration::Module(_)) => {}
            }
        }
        ty @ ExpressionType::Collection(col_ty) => {
            let ty = ty.clone();

            let runtime_fns = match col_ty {
                CollectionType::Array(_) => &declarations.array_intrinsics,
                CollectionType::Dict(_, _) => &declarations.dict_intrinsics,
                CollectionType::ReferenceCounter(_) => &declarations.rc_intrinsics,
                CollectionType::Cell(_) => &declarations.cell_intrinsics,
                CollectionType::String => todo!(),
            };

            let runtime_fn = &runtime_fns[func_name.as_str()];

            let mut temp_lhs = HirNode::dummy();
            std::mem::swap(lhs as &mut HirNode, &mut temp_lhs);

            match &temp_lhs.ty {
                // Don't double-wrap the expression in pointers
                ExpressionType::Pointer(ptr_ty, _) => {
                    if runtime_fn.ptr_ty == PointerKind::UniqueRef
                        && *ptr_ty != PointerKind::UniqueRef
                    {
                        todo!("unhandled case: wrong kind of pointer for collection method")
                    }
                }
                _ => {
                    temp_lhs = HirNode::autogenerated(
                        HirNodeValue::TakePointer(runtime_fn.ptr_ty, Box::new(temp_lhs)),
                        ExpressionType::Pointer(PointerKind::SharedRef, Box::new(ty)),
                    );
                }
            }

            let mut runtime_args = Vec::new();
            std::mem::swap(args, &mut runtime_args);
            runtime_args.insert(0, temp_lhs);

            std::mem::swap(
                root,
                &mut HirNode::generated_with_id(
                    root.id,
                    HirNodeValue::IntrinsicCall(runtime_fn.intrinsic_fn, runtime_args),
                    root_ty.clone(),
                ),
            );
        }
        ExpressionType::Generator { .. } => {}
        ty => unreachable!(
            "illegal lhs of access in function call: {:?} in {:?}",
            ty, lhs
        ),
    }
}
